### ISSUE TITLE
Problem with simulator

### ISSUE THREAD

**Issue by anfontanelli** [jhu-dvrk/dvrk-ros#16]
Hi,
i have a problem when i launch the simulator. For example if i launch file ecm.launch i have the following errors "No such file or directory: '/home/andrea/catkin_ws/src/dvrk-ros/dvrk_model/model/ecm.xacro'.
I follow the github tutorial.
Can you help me please?
Tanks

**Comment by adeguet1** [comment]
Can you confirm with launch script you're using?  And maybe which branch you're using?

There has been multiple implementations to simulate a dVRK arm, some completely parallel to the cisst-SAW implementation.  In the recent past, I added a simple geometric simulation mode within the cisst-SAW classes.  I just updated the dvrk_robot README.md to show how to create a simulated arm: https://github.com/jhu-dvrk/dvrk-ros/blob/master/dvrk_robot/README.md

I also updated the main dvrk_ros README.md to document the content of each directory.

**Comment by anfontanelli** [comment]
Dear adeguet1, thank you for your reply.

Actually I am not so skilled with ros.
I just followed the Readme (https://github.com/jhu-dvrk/dvrk-ros/blob/master/README.md) to build the cisst workspace. After I cloned the master branch of dvrk-ros and tryed the following command:
roslaunch dvrk_model ecm.launch. This was just a test, I am actually unable to run all the launch file specified in the launch directory with similar errors. 

There is another more stablet branch or some walkthrought that I can follow?
Ps I am using ROS indigo on Ubuntu 14.04.

**Comment by adnanmunawar** [comment]
This issue is related to the ecm.xacro file missing in the dvrk-ros/dvrk_model/model/ecm.xacro folder. There has been a lot of changes at this repos and some resulted in broken launch files. This needs to fixed.

As far as your issue is concerned, there are a few ways to get around this problem. The easiest is to open a text editor and change your launch file, change the instances that read "ecm.xacro" to "ECM.xacro". See if this solves your problem.

**Comment by adnanmunawar** [comment]
This issue is related to the ecm.xacro file missing in the dvrk-ros/dvrk_model/model/ecm.xacro folder. There has been a lot of changes at this repos and some resulted in broken launch files. This needs to fixed.

As far as your issue is concerned, there are a few ways to get around this problem. The easiest is to open a text editor and change your launch file, change the instances that read "ecm.xacro" to "ECM.urdf.xacro". See if this solves your problem.

**Comment by zchen24** [comment]
For kinematics simulation, please follow the doc here [Kinematics Simulation](/jhu-dvrk/sawIntuitiveResearchKit/wiki/Kinematics-Simulation)
